### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Lucifirius** [Pyfa-fit/Pyfa-fit#50]
```
OS version: 	Windows-10-10.0.14393-SP0
Python: 	2.7.13
wxPython: 	3.0.2.0
SQLAlchemy: 	1.1.9
Logbook: 	1.0.0
pyfa version: 2017.04.13 (release) - YC119.3 1.0
pyfa root: C:\Users\jacob\DOCUME~1\Programs\pyfa-fit
save path: C:\Users\jacob\.pyfa
fs encoding: mbcs

EXCEPTION: C++ assertion "m_menuDepth > 0" failed at ..\..\src\msw\toplevel.cpp(1544) in wxTopLevelWindowMSW::DoSendMenuOpenCloseEvent(): No open menus?

  File "site-packages\wx-3.0-msw\wx\_core.py", line 16766, in <lambda>
  File "gui\builtinViews\fittingView.py", line 547, in spawnMenu
  File "site-packages\wx-3.0-msw\wx\_core.py", line 11144, in PopupMenu

```

It happens when I right click on a cap booster, go to the charges (all) menu, and click out.

**Comment by Ebag333** [comment]
Thanks for reporting.

Can't replicate, but guessing it's a race condition where the context menu gets destroyed before it's fully loaded.

We're catching a lot of these because we added the notification. They were always happening, we just didn't know about it. :)

Anyway, we can catch and handle it so it doesn't throw exceptions.
